PC=fpc
PFLAGS=-Miso

clean:
	rm -rfv *.o *.exe

all: Appears.exe

Appears.exe: Appears.pas
	$(PC) $(PFLAGS) -o$@ $<
Equal.exe: Equal.pas
	$(PC) $(PFLAGS) -o$@ $<
Length.exe: Length.pas
	$(PC) $(PFLAGS) -o$@ $<
ReadString.exe: ReadString.pas
	$(PC) $(PFLAGS) -o$@ $<
WriteString.exe: WriteString.pas
	$(PC) $(PFLAGS) -o$@ $<
