PC=fpc
PFLAGS=-Miso

clean:
	rm -rfv *.o *.exe

all: 

Binary.exe: Binary.pas
	$(PC) $(PFLAGS) -o$@ $<
Linear.exe: Linear.pas
	$(PC) $(PFLAGS) -o$@ $<
Quadratic.exe: Quadratic.pas
	$(PC) $(PFLAGS) -o$@ $<
Search.exe: Search.pas
	$(PC) $(PFLAGS) -o$@ $<
StateSearch.exe: StateSearch.pas
	$(PC) $(PFLAGS) -o$@ $<
