PC=fpc
PFLAGS=-Miso

clean:
	rm -rfv *.o *.exe

all: Caller.exe Conflict.exe Doggerel.exe ReverseInput.exe SplitUp.exe Switch.exe ValueArg.exe ValueBed.exe VarArg.exe WiseGuy.exe

Caller.exe:
	$(PC) $(PFLAGS) -o$@ Caller.pas

Conflict.exe:
	$(PC) $(PFLAGS) -o$@ Conflict.pas

Doggerel.exe:
	$(PC) $(PFLAGS) -o$@ Doggerel.pas

ParamBed.exe:
	$(PC) $(PFLAGS) -o$@ ParamBed.pas

ReverseInput.exe:
	$(PC) $(PFLAGS) -o$@ ReverseInput.pas

SplitUp.exe:
	$(PC) $(PFLAGS) -o$@ SplitUp.pas

Switch.exe:
	$(PC) $(PFLAGS) -o$@ Switch.pas

ValueArg.exe:
	$(PC) $(PFLAGS) -o$@ ValueArg.pas

ValueBed.exe:
	$(PC) $(PFLAGS) -o$@ ValueBed.pas

VarArg.exe:
	$(PC) $(PFLAGS) -o$@ VarArg.pas

WiseGuy.exe:
	$(PC) $(PFLAGS) -o$@ WiseGuy.pas

